# -*- coding: utf-8 -*-
# voxapi/core/tts_local.py
"""
# tts 语音克隆使用 voxcpm 代码示例（来自官方）

import voxcpm
import soundfile as sf

model = VoxCPM.from_pretrained(
  "openbmb/VoxCPM2",
  load_denoiser=False,
)

# 语音设计 （可能后续会替代edge-tts）
wav = model.generate(
    text="(A young woman, gentle and sweet voice)Hello, welcome to VoxCPM2!",
    cfg_value=2.0,
    inference_timesteps=10,
)
sf.write("voice_design.wav", wav, model.tts_model.sample_rate)

# 上传参考音频。该模型会复制音色，您仍然可以使用控制指令来调整速度、情感或风格
wav = model.generate(
    text="This is a cloned voice generated by VoxCPM2.",
    reference_wav_path="path/to/voice.wav",
)
sf.write("clone.wav", wav, model.tts_model.sample_rate)

wav = model.generate(
    text="(slightly faster, cheerful tone)This is a cloned voice with style control.",
    reference_wav_path="path/to/voice.wav",
    cfg_value=2.0,
    inference_timesteps=10,
)
sf.write("controllable_clone.wav", wav, model.tts_model.sample_rate)

# 请同时提供参考音频及其精确的文本，以便进行基于音频延续的克隆，确保还原每一个声音细微差别。为了获得最佳克隆效果，请将同一个参考音频片段同时传递给 reference_wav_path 和 prompt_wav_path ，如下所示：
wav = model.generate(
    text="This is an ultimate cloning demonstration using VoxCPM2.",
    prompt_wav_path="path/to/voice.wav",
    prompt_text="The transcript of the reference audio.",
    reference_wav_path="path/to/voice.wav", # optional, for better simliarity
)
sf.write("hifi_clone.wav", wav, model.tts_model.sample_rate)


# 4. 流媒体API
import numpy as np

chunks = []
for chunk in model.generate_streaming(
    text="Streaming text to speech is easy with VoxCPM!",
):
    chunks.append(chunk)
wav = np.concatenate(chunks)
sf.write("streaming.wav", wav, model.tts_model.sample_rate)

"""

from voxcpm import VoxCPM

from configs.config import settings
from loguru import logger

# tts model 全局唯一实例
_GLOBAL_TTS_MODEL = None

def get_tts_model():
    global _GLOBAL_TTS_MODEL
    # model path: voxcpm2_path  voxcpm15_path
    model_path = settings.voxcpm2_path
    logger.info(f"⏳ Loading TTS model from {model_path}")
    if _GLOBAL_TTS_MODEL is None:
        _GLOBAL_TTS_MODEL = VoxCPM.from_pretrained(
            model_path,
            load_denoiser=False
        )
    logger.success(f"✅ Loading TTS model from {model_path}")
    return _GLOBAL_TTS_MODEL



if __name__ == "__main__":
    # 测试用例

    tts_engine = get_tts_model()









